use_frameworks!

platform :ios, '10.0'

target 'nRFMeshProvision_Example' do
  pod 'nRFMeshProvision', :path => '../'
  pod 'LookinServer', :configurations => ['Debug']
  target 'nRFMeshProvision_Tests' do
    inherit! :search_paths
  end
end
