use_frameworks!

platform :ios, '13.0'

target 'nRF Mesh' do
  pod 'nRFMeshProvision', :path => '../'
  pod 'LookinServer', :configurations => ['Debug']
  target 'nRF Mesh Tests' do
    inherit! :search_paths
  end
end
