name: Feature request
description: Propose a new feature.
labels: ["improvement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: dropdown
    id: type
    attributes:
      label: Target
      description: Are you proposing it a feature in nRF Mesh app or the library?
      options:
        - Library
        - App
      default: 0
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Describe the feature
      description: What do you need? You may include screenshots if needed.
      placeholder: Please add...
    validations:
      required: true